### PR TITLE
[XBEAN-339] Upgrade to ASM 9.5

### PR DESCRIPTION
**Pull request by LuciferYang**
This pr aims to upgrade ASM from 9.4 to 9.5

### CODE REVIEW

**Review by rmannibucau — APPROVED** [review]

**Comment by LuciferYang** [comment]
Thanks @rmannibucau ~

**Comment by LuciferYang** [comment]
@rmannibucau Is it possible to release a new version of Apache geronimo-xbean? I hope to upgrade the `xbean-asm9-shaded` dependency in Apache Spark with ASM 9.5. Thanks ~

**Comment by fpapon** [comment]
@rmannibucau I can manage the release if needed

**Comment by LuciferYang** [comment]
Thanks @fpapon

**Pull request merged**
