### PR TITLE
[XBEAN-345] Upgrade ASM from 9.6 to 9.7

### PR DESCRIPTION
**Pull request by panbingkun**
The pr aims to upgrade `ASM` from `9.6` to `9.7`, the new version is for Java `23`.

### CODE REVIEW

**Comment by panbingkun** [comment]
`mvn clean install` with JDK1.8
image

**Comment by panbingkun** [comment]
cc @rmannibucau @fpapon

**Comment by panbingkun** [comment]
https://asm.ow2.io/versions.html
image

**Comment by panbingkun** [comment]
@rmannibucau Thank you very much!
Please don't mind, I would like to ask if there is a `release date` for our new version based on `ASM 9.7`?

**Comment by fpapon** [comment]
> @rmannibucau Thank you very much! Please don't mind, I would like to ask if there is a `release date` for our new version based on `ASM 9.7`?

Hi @panbingkun 
I will try to run the release process this week, I'll keep you posted.

**Comment by panbingkun** [comment]
> > @rmannibucau Thank you very much! Please don't mind, I would like to ask if there is a `release date` for our new version based on `ASM 9.7`?
> 
> Hi @panbingkun I will try to run the release process this week, I'll keep you posted.

Thank you! ❤️

**Pull request merged**
