### PR TITLE
[XBEAN-347] Upgrade ASM from 9.7 to 9.7.1

### PR DESCRIPTION
**Pull request by panbingkun**
The pr aims to upgrade `ASM` from `9.7` to `9.7.1`, the new version is for Java 24.

### CODE REVIEW

**Comment by panbingkun** [comment]
image

```
mvn clean install
```
image

**Comment by panbingkun** [comment]
https://asm.ow2.io/versions.html
image

**Comment by panbingkun** [comment]
cc @rmannibucau @fpapon

**Review by fpapon — APPROVED** [review]
@panbingkun thanks for your contribution!

**Comment by fpapon** [comment]
I will launch the release process soon.

**Comment by panbingkun** [comment]
> I will launch the release process soon.

Thank you very much! ❤️

**Comment by fpapon** [comment]
@panbingkun release done and available on Central.

**Comment by panbingkun** [comment]
> @panbingkun release done and available on Central.

@fpapon Good job, thank you very much!

**Pull request merged**
