### PR TITLE
[XBEAN-341] Upgrade ASM from 9.5 to 9.6

### PR DESCRIPTION
**Pull request by LuciferYang**
This pr aims to upgrade ASM from 9.5 to 9.6, the new version is for Java 22.

### CODE REVIEW

**Comment by LuciferYang** [comment]
Local check `mvn clean install` with Java 8, all tests can pass.

**Review by fpapon — APPROVED** [review]
LGTM
@LuciferYang thanks for your contribution!

**Comment by LuciferYang** [comment]
Thanks @fpapon ~

**Comment by fpapon** [comment]
Release should be perfomed soon

**Pull request merged**
